controllers:
    resource: ../src/Controller/
    type: attribute


# config/routes.yaml
send_mail:
    path: /contact/send_mail
    controller: App\Controller\ContactController::sendMail
    methods: [POST]


# config/routes.yaml
horaires_edit:
    path: '/horaires/edit'
    controller: 'App\Controller\HorairesController::edit'
    methods: ['GET', 'POST']


# config/routes.yaml
garage_info_contact:
    path: '/garage-info/contact'
    controller: App\Controller\GarageInfoController::contact


admin_products_delete:
    path: '/admin/produits/suppression/{id}'
    controller: 'App\Controller\Admin\ProductsController::delete'
    methods: ['POST']

categories_list:
    path: '/categories/{slug}'
    controller: 'App\Controller\CategoriesController::details'

